### ISSUE TITLE
shown graph jumps down while moving.

### ISSUE THREAD

**Issue by JonasFehrenbach** [PSEProgrammgraphen/GraphVonAnsicht#12]
While trying to move the graph in the graphview with "CTRL" and "Right MouseClick", the graph always jumps down a few pixels at the beginning.

**Comment by Nicolas-Boltz** [comment]
Fixed. Wrong value was used for calculating the new position of the view.

event.getSceneX/Y has a value slightly higher than the value from event.getX/Y, which caused the jumping.

Linked wrong issue in commit message(#31)
