### ISSUE TITLE
Filter of some Vertex types leads to NullPointerException

### ISSUE THREAD

**Issue by thatUserjm** [PSEProgrammgraphen/GraphVonAnsicht#17]
File: Fields.pdg.graphml, Filter(vertex): EXPR or NORM:
NullPointerException with getLayer() in SugiyamaGraph...through LayerAssigner

**Comment by heho** [comment]
This seams to be an issue with vertices that are in a constraint since they are not deleted from there

**Comment by Lucas-Steinmann** [comment]
Seems to be fixed with commit 545bd7119837783598a614cc6bb64f8cf3c56f80 where the constraints for the MethodGraph are no longer used for the individual FieldAccessGraphs
Issue #25 is still open.
