### ISSUE TITLE
FieldAccessGraph got extra edgeSet for adding edges to it

### ISSUE THREAD

**Issue by thatUserjm** [PSEProgrammgraphen/GraphVonAnsicht#18]
It would be better if all edges that belong to the FieldAccess were added when creating a FieldAccess and its -Graph. Then the addEdge method and the edge parameter is not necessary anymore.

**Comment by Lucas-Steinmann** [comment]
Resolved with commit e533f7d86c3d286bc7be562732959a85fea01fbf
