### ISSUE TITLE
Textlabel in svg export is longer than the vertex box

### ISSUE THREAD

**Issue by JonasFehrenbach** [PSEProgrammgraphen/GraphVonAnsicht#27]
The label of the vertices in the exported .svg file is longer than the vertex box.
Maybe the font size of the .svg is bigger than the font size in the graphview.

**Comment by thatUserjm** [comment]
Issue occurs again. (commit hash ff7a1c862ecdb13aa8d4187bba3fde80f9a0c60e):
Graph `com.ibm.wala.FakeRootClass.fakeRootMethod()V` in file `SmallControl.pdg.graphml`.
In addition here were vertices of kind NORM filtered.
This is the resulting exported file:
![export fehler](https://cloud.githubusercontent.com/assets/19251666/17743293/88de5e72-64a3-11e6-9578-93b6f1f8721e.PNG)

This the actual view before exporting:
![fehler export soll](https://cloud.githubusercontent.com/assets/19251666/17743332/a23a04ca-64a3-11e6-97cd-399e4725be99.PNG)
