### ISSUE TITLE
Redrawing hides colouring of groups

### ISSUE THREAD

**Issue by marcelrad** [PSEProgrammgraphen/GraphVonAnsicht#29]
Mark a vertex or a group of vertices. Add some vertices to a group and select a colour. Choose Layout -> Change algorithms and apply a drawing algorithm. The new drawing does not show the colouring of the groups. 
Group before redrawing
![screenshot from 2016-08-12 08 55 26](https://cloud.githubusercontent.com/assets/458451/17615926/bdbf74b8-6071-11e6-9568-e4208ed31380.png)
Group after redrawing:
![screenshot from 2016-08-12 08 55 33](https://cloud.githubusercontent.com/assets/458451/17615925/bdbb9e74-6071-11e6-9e00-4ced0e550be9.png)

Expected result: Colouring is persistent,
Graph: SmallControll
Method SmallControll.main
Version/Git-Hash: 196244f554017bd9b0c81c6b3461c109cd17376b

**Comment by ratefuchs** [comment]
Additionally, even if I change that group's color in the "groups" dialog, the coloring cannot be brought back.
