### ISSUE TITLE
edge reversing after graph layout not working

### ISSUE THREAD

**Issue by heho** [PSEProgrammgraphen/GraphVonAnsicht#40]
When layouting the same graph several times it can be noticed that some edges are reversed.

![graph01](https://cloud.githubusercontent.com/assets/372640/17671538/c7c5e098-6317-11e6-8341-51fb1bdff2ee.PNG)
most edges go into the selected vertex

![graph02](https://cloud.githubusercontent.com/assets/372640/17671539/c7c82efc-6317-11e6-9c4f-0d36ae88e8c7.PNG)
all edges come out of the selected vertex

**Comment by thatUserjm** [comment]
This issue seems to appear only after layouting the graph again.
After the first layouting the direction of every edge seems to be correct.

**Comment by thatUserjm** [comment]
After testing a few times the testfile Control.pdg.graphml and the MethodGraph Control.test2() there is, without relayouting, only after importing and first layouting always only one reversed edge in the sugiyama classes while layouting. And nevertheless the direction of edges changes.
The error might be in setting and reckognizing reversed edges in the whole sugiyama.
