### ISSUE TITLE
CrossMinimizer calculation time could be improves by settings.

### ISSUE THREAD

**Issue by thatUserjm** [PSEProgrammgraphen/GraphVonAnsicht#47]
The CrossMinimizer takes a long time to calculate the crossings of a given graph.
If there would be an option to just let the CrossMinimizer run a certain amount of times instead of calculating the amount of crossings this calculation time could be avoided.

**Comment by heho** [comment]
The user can now effectively choose the number of crossMinimizer runs and whether he wants to use the crossings reduction threshold. There is no "intelligent run number" option yet. Will be postponed after release
