### ISSUE TITLE
Edge Filtering not working correctly

### ISSUE THREAD

**Issue by heho** [PSEProgrammgraphen/GraphVonAnsicht#5]
When using edge Filters, after the initial selection of filters. Unchecking of an Edge Type wont show more Edges. However Ticking sometimes does, albeit only one edge type a time. Can best be observed by using a small test graph.

**Comment by Lucas-Steinmann** [comment]
cannot reproduce this in newer version. 
Is this bug still present?
If yes can you provide an example file?

**Comment by thatUserjm** [comment]
Bug not present anymore.
