### ISSUE TITLE
Hidden vertex

### ISSUE THREAD

**Issue by Lucas-Steinmann** [PSEProgrammgraphen/GraphVonAnsicht#51]
In the model of Fields.pdg.graphml in the graph of method Fields.t2() two vertices are drawn on the same spot, resulting in one vertex being hidden.
On selection the information for both vertices are shown in the information view.
![hiddenvertex](https://cloud.githubusercontent.com/assets/5488609/17777190/ddc0196e-655f-11e6-893f-5602215adaff.png)

**Comment by heho** [comment]
Fixed. Segments in Vertex Positioner could contain edges that connect vertices that are on the same layer. When aligning them these vertices wound up on the same position.
