### ISSUE TITLE
Crossings in call graph even if it is a tree

### ISSUE THREAD

**Issue by ratefuchs** [PSEProgrammgraphen/GraphVonAnsicht#52]
When opening `Flow.pdg.graphml`, i sometimes get a layout like in this picture:

![crossings](https://cloud.githubusercontent.com/assets/1158701/17804529/52c51740-65fc-11e6-8f3e-ce854a7fe2a9.png)
There is an unnecessary crossing even though the call graph is a tree (which should make avoiding crossings much easier). In this picture, the crossing could have been prevented by simply moving the bottom right node to the bottom left.
This issue persists even if I toggle "Use threshold" on and off.

**Comment by heho** [comment]
It can not be garantied, that this wont happen, however it is very much less likely with the new default settings.
