### ISSUE TITLE
Size of fieldaccess is wrong after filtering

### ISSUE THREAD

**Issue by JonasFehrenbach** [PSEProgrammgraphen/GraphVonAnsicht#54]
Process: 
1. Open graphml file ManyParams.pdg.graphml
2. Open methodgraph java.io.PrintStream.newLine()V
3. Add edge filter CD, CE, CF, CL

Result:
![picture](https://cloud.githubusercontent.com/assets/19250543/17831546/0c657d58-66ec-11e6-918b-ab4e1388ce16.jpg)

.

**Comment by thatUserjm** [comment]
now it appears a NullPointerException after filtering edges contained in a FieldAccess
