### ISSUE TITLE
It is possible to Collapse Vertices of different fieldaccesses together

### ISSUE THREAD

**Issue by heho** [PSEProgrammgraphen/GraphVonAnsicht#56]
You can select vertices in different FieldAccesses and collapse them together. Is this a wanted functionality?

**Comment by Lucas-Steinmann** [comment]
In future a selection can only be collapsed if it fulfills one of these criteria:

- The selection is a subset of exactly one FieldAccess
- The selection is distinct to all FieldAccesses
- The selection is a superset of every FieldAccess it intersects

To answer your question: You should from now on be able to select two FieldAccess and collapse them together. But every vertex of the FieldAccesses has to be selected. 
Selecting only some vertices of two different FieldAccesses and collapsing them should no longer be possible from now on.
