### ISSUE TITLE
No loop is drawn in callgraph.

### ISSUE THREAD

**Issue by JonasFehrenbach** [PSEProgrammgraphen/GraphVonAnsicht#57]
Open `Fibonacci.pdg.graphml`.
The result is:
![fib-fail](https://cloud.githubusercontent.com/assets/19250543/17838124/5fa5bfc6-67c5-11e6-9cef-46f75cd1ebbd.jpg)

But compared with the Joana GraphViewer there should be a loop at the node `Fibonacci.pow([], int)` (node id=160 in .graphml File).
So it should look like this (the missing edge is red):
![fib-correct](https://cloud.githubusercontent.com/assets/19250543/17838137/9eef7d52-67c5-11e6-8eed-2181e91a553f.jpg)

I searched through the `Fibonacci.pdg.graphml` with a text editor, but could not find the loop. Furthermore i could not find the loop in `Fibonacci.pdg` with a text editor.
I have no idea how the Joana GraphViewer identify this loop...

**Comment by ratefuchs** [comment]
The two call edges 182->160 and 196->160 should lead to this cycle.

**Comment by JonasFehrenbach** [comment]
Ok thanks, 
I added the missing callEdges to the CallGraph. (There was a problem that a loop could not get found during import).

But there is a little layout problem with the loop:
![fib-work](https://cloud.githubusercontent.com/assets/19250543/17851287/765ae7f4-6861-11e6-9330-ca03a71abdaf.jpg)

Maybe @thatUserjm or @heho can fix this problem in the CallGraphLayout.
