### ISSUE TITLE
Collapsing does not work anymore

### ISSUE THREAD

**Issue by ratefuchs** [PSEProgrammgraphen/GraphVonAnsicht#64]
In b88ba80, Open `Flow.pdg.graphml` and collapse the three `java.io` methods. The following wrong layout appears:

![collapse](https://cloud.githubusercontent.com/assets/1158701/17861348/fa9c227e-6890-11e6-8ac4-730ac5ac08a3.png)

**Comment by Nicolas-Boltz** [comment]
already fixed with commit 05e2938
