### ISSUE TITLE
Add a default filter for first layout.

### ISSUE THREAD

**Issue by JonasFehrenbach** [PSEProgrammgraphen/GraphVonAnsicht#70]
By opening a Methodgraph for the first time, some edges should automatically be filtered by default.

**Comment by Nicolas-Boltz** [comment]
@mhecker can you give us a suggestion for the default filtered edges?

**Comment by ratefuchs** [comment]
The current JOANA graph viewer filters out three kinds of edges when first opening a graph, namely
CF, HE and PS.
