### ISSUE TITLE
Why are so many edges going into a FieldAccess ?

### ISSUE THREAD

**Issue by thatUserjm** [PSEProgrammgraphen/GraphVonAnsicht#75]
In file `BigField.pdg.graphml` and graph `BigField.main()` there are many edges coming into a FieldAccess into Vertex "field" with id=11, marked below.
The amount of incoming edges into this vertex is about the amount of FieldAccesses contained in this MethodGraph.
![fieldaccessmanyedges](https://cloud.githubusercontent.com/assets/19251666/17947122/96b5700a-6a4b-11e6-9b29-c3744929976c.PNG)

Thsi may cause Problems in representing the vertices and edges in a FieldAccess if the amount of edges coming in or going out of a FieldAccess is not constant.
Does this occur often if a graph contains many FieldAccesses or is this maybe not correct ?

**Comment by ratefuchs** [comment]
While you cannot assume the number of field accesses to be constant, this many edges might be rare. The number of field accesses is not the deciding factor here but the structure.
The Java program from which this PDG was created is (shortened):
`b.x = b;`
`b.i = 1;`
`System.out.println(b.x.x.x.[...].x.i);`
As such, edges from the field write to `x` in the first line to all field reads from `x` are generated.

**Comment by thatUserjm** [comment]
Even if this amount of edges coming into a FieldAccess-box is very rare what could be an appripriate representation for this much edges ?
Drawing each of them into this box with a small space between each other would make the FieldAccess' box very wide.

**Comment by ratefuchs** [comment]
I don't really think this problem is specific for field accesses. It always is problematic when a vertex has many incoming or outgoing edges.I see no good solution for that though...

**Comment by thatUserjm** [comment]
Now with the default filter settings there are shown much less edges in a FieldAccess so it looks way better.
If the user nevertheless disables all filter settings he will get the problem described above.
